Buttons1:
  Text: '[Yes]'
  Color: BLUE
  Bold: true
  ClickEvent:
    Action: RUN_COMMAND
    Text: /cd reload
  HoverEvent:
    Action: SHOW_TEXT
    Text:
      - 'reload.'
Buttons2:
  Text: '[No]'
  Color: GOLD
  Bold: false
  ClickEvent:
    Action: RUN_COMMAND
    Text: /cd cast buttonNo
  HoverEvent:
    Action: SHOW_TEXT
    Text:
      - 'NO!'

PlayerHealth:
  Text: '&chat_self_health_proportion_10&'

PlayerName:
  Text: '&chat_name&'
  Color: 4076D4
  ShowText:
    - '{#478504}Click to have a private chat with the player'
  ClickEvent:
    Action: SUGGEST_COMMAND
    Text: '/msg &chat_name& '
